// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/91647767d2fff5cd269631f9d1eeb2681cfc8d98/serialport/index.d.ts
declare module 'serialport' {
    class SerialPort {
        constructor(path: string, options?: Object, openImmediately?: boolean, callback?: (err: any) => void)
        isOpen(): boolean;
        on(event: string, callback?: (data?: any) => void): void;
        open(callback?: (err: any) => void): void;
        write(buffer: any, callback?: (err: any, bytesWritten: number) => void): void
        pause(): void;
        resume(): void;
        disconnected(err: Error): void;
        close(callback?: (err: any) => void): void;
        flush(callback?: (err: any) => void): void;
        set(options: SerialPort.setOptions, callback: (err: any) => void): void;
        drain(callback?: (err: any) => void): void;
        update(options: SerialPort.updateOptions, callback?: (err: any) => void): void;
        static list(callback: (err: any, ports: SerialPort.portConfig[]) => void): void;
        static parsers: {
            readline: (delimiter: string) => void,
            raw: (emitter: any, buffer: string) => void
        };
    }

    namespace SerialPort {
        interface portConfig {
            comName: string;
            manufacturer: string;
            serialNumber: string;
            pnpId: string;
            locationId: string;
            vendorId: string;
            productId: string;
        }

        interface setOptions {
            brk?: boolean;
            cts?: boolean;
            dsr?: boolean;
            dtr?: boolean;
            rts?: boolean;
        }

        interface updateOptions {
            baudRate?: number;
        }
    }

    export = SerialPort;
}
